?start: document

document: key_chord        
key_chord: WS* (key)? WS* chord
key: KEY

chord: ( chord_component ( "/" tonality_component )* )
chord_component: ( special_chord | standard_chord ) chord_alteration*
tonality_component: [chord_accidental] numeral
special_chord: SPECIAL_CHORD [ inversion ]
standard_chord: [ chord_accidental ] numeral [ CHORD_QUALITY ] [ inversion ]
numeral: ROMAN_NUMERAL
chord_accidental: ACCIDENTAL
CHORD_QUALITY: "o" | "+" | "%" | "ø" | "°"
chord_alteration: "[" alteration_content "]"
omit_alteration: "no"
add_alteration: "add"
alteration_content: (( omit_alteration | add_alteration )? ACCIDENTAL? DIGITS)

KEY: /[A-Ga-g](#{1,}|b{1,})?:/
SPECIAL_CHORD: "Ger" | "It" | "Fr" | "N" | "Cad" | "NC" | "R" | "r"
ROMAN_NUMERAL: "I" | "II" | "III" | "IV" | "V" | "VI" | "VII"
             | "i" | "ii" | "iii" | "iv" | "v" | "vi" | "vii"
ACCIDENTAL: /#{1,}|b{1,}/

inversion: INVERSION_STANDARD | inversion_free
INVERSION_STANDARD: "6" | "64" | "6/3" | "6/4" | "7" | "6/5" | "65" | "4/3" | "43" | "2" | "42" | "4/2" | "9" | "11" | "13"
inversion_free: ACCIDENTAL? DIGIT+

DIGIT: /[0-9]/
DIGITS: DIGIT+
LETTER: /[a-z]+/

WS: (" " | /\t/)+
CR: /\r/
LF: /\n/
NEWLINE: WS* (CR? LF)+

%ignore NEWLINE
%ignore CR
%ignore LF
%ignore WS