?start: document

document: (NEWLINE)* line*
line: metadata_line
     | statement_line

metadata_line: composer_line
             | title_line
             | time_signature_line
             | tempo_line
             | instrument_line

composer_line: "Composer:" WS REST_LINE NEWLINE
title_line: "Piece:" WS REST_LINE NEWLINE
time_signature_line: ( "(" WS*  "m" MEASURE_NUMBER WS* ")" WS*)? "Time Signature" WS* ":" WS* time_signature NEWLINE
tempo_line: "Tempo:" WS* TEMPO_NUMBER NEWLINE  // Tempo number in QPM
instrument_line: "Instrument:" WS TRACK_NAME WS* "=" WS* GM_INSTRUMENT_NAME ("," WS* TRACK_NAME WS* "=" WS* GM_INSTRUMENT_NAME)* NEWLINE

TRACK_NAME: "T" DIGIT+
GM_INSTRUMENT_NAME: /[a-zA-Z_1-9]+/
TEMPO_NUMBER: DIGIT+

statement_line: measure_line
              | note_line
              | melody_line
              | event_line
              | variable_declaration_line
              | technique_line


technique_line: "tech" WS (voice_list_for_technique | single_voice_for_technique) WS+ measure_range_with_beats WS* ":" WS* technique_list NEWLINE
voice_list_for_technique: "[" WS* TRACK_NAME ("," WS* TRACK_NAME)* WS* "]"
single_voice_for_technique: TRACK_NAME
measure_range_with_beats: "(" MEASURE_INDICATOR WS+ BEAT_INDICATOR WS+ "-" WS MEASURE_INDICATOR WS+ BEAT_INDICATOR ")"
technique_list: TECHNIQUE_NAME ("," WS* TECHNIQUE_NAME)*
TECHNIQUE_NAME: /[a-zA-Z_][a-zA-Z0-9_]*/

variable_declaration_line: VARIABLE_NAME WS* "=" WS* variable_content NEWLINE
variable_content: ( melody_line_content | measure_line_content)
VARIABLE_NAME: /[_a-zA-Z][_a-zA-Z0-9]*/
VARIABLE_VALUE: REST_LINE
VARIABLE_CALLING: "@" VARIABLE_NAME

event_line: "e" MEASURE_NUMBER WS* event_content+ NEWLINE
event_content: BEAT_INDICATOR WS* EVENT_FUNCTION_NAME + "(" + EVENT_ARGUMENT + ")"
EVENT_FUNCTION_NAME: "tempo" | "velocity" | "start_crescendo" | "end_crescendo" | "start_diminuendo" | "end_diminuendo" | "start_accelerando" | "end_accelerando" | "start_ritardando" | "end_ritardando"
EVENT_ARGUMENT: TEMPO_NUMBER | VELOCITY_VALUE
VELOCITY_VALUE: "pppp" | "ppp" | "pp" | "p" | "mp" | "mf" | "f" | "ff" | "fff" | "ffff"

measure_line: MEASURE_INDICATOR (measure_line_content|VARIABLE_CALLING) NEWLINE
measure_line_content: (chord_beat_1)? (beat_chord | key_change)* PHRASE_BOUNDARY?
chord_beat_1: (WS key)? WS chord
beat_chord: WS BEAT_INDICATOR (WS key)? WS chord
key_change: WS key
key: KEY


note: NOTELETTER ACCIDENTAL?
NOTELETTER: /[A-Ga-g]/

note_line: "Note:" WS REST_LINE NEWLINE

chord: ( chord_component ( "/" tonality_component )* )
chord_component: ( special_chord | standard_chord ) chord_alteration*
tonality_component: [chord_accidental] numeral
special_chord: SPECIAL_CHORD [ inversion ]
standard_chord: [ chord_accidental ] numeral [ CHORD_QUALITY ] [ inversion ]
numeral: ROMAN_NUMERAL
chord_accidental: ACCIDENTAL
CHORD_QUALITY: "o" | "+" | "%" | "ø" | "°"
chord_alteration: "[" alteration_content "]"
omit_alteration: "no"
add_alteration: "add"
alteration_content: (( omit_alteration | add_alteration )? ACCIDENTAL? DIGITS)

voice_list: (ALTERATION? VOICE OCTAVE?)+
VOICE: /[1-4]/
// Delta octave
OCTAVE: "o" SIGNED_INT 
// Delta alteration (semitones)
ALTERATION: ("+" | "-")+

melody_line: MEASURE_INDICATOR (WS+ TRACK_NAME)? (melody_line_content | VARIABLE_CALLING) NEWLINE
melody_line_content: (first_beat_note)? (beat_note)*
first_beat_note: WS+ (BEAT_INDICATOR WS+)? (ABSOLUTE_NOTE+ | SILENCE | CONTINUATION | voice_list) note_techniques?
beat_note: WS+ BEAT_INDICATOR WS (ABSOLUTE_NOTE+ | SILENCE | CONTINUATION | voice_list) note_techniques?
note_techniques: "[" WS* TECHNIQUE_NAME ("," WS* TECHNIQUE_NAME)* WS* "]"
SILENCE: "r" | "R"
CONTINUATION: "L" | "l"
ABSOLUTE_NOTE: NOTELETTER_CAPITALIZED (ACCIDENTAL)? (ABSOLUTE_OCTAVE)?
NOTELETTER_CAPITALIZED: /[A-G]/
ABSOLUTE_OCTAVE: DIGIT+

MEASURE_INDICATOR: "m" MEASURE_NUMBER
MEASURE_NUMBER: DIGIT+ (LETTER+ | "var" DIGIT+)? 
BEAT_INDICATOR: "b" BEAT_NUMBER
BEAT_NUMBER: DIGIT+ ("." DIGIT+)?

time_signature: numerator "/" denominator
numerator: DIGIT+
denominator: DIGIT+
SIGNED_INT: ("+"|"-")? DIGIT+

KEY: /[A-Ga-g](#{1,}|b{1,})?:/
SPECIAL_CHORD: "Ger" | "It" | "Fr" | "N" | "Cad" | "NC" | "R" | "r"
ROMAN_NUMERAL: "I" | "II" | "III" | "IV" | "V" | "VI" | "VII"
             | "i" | "ii" | "iii" | "iv" | "v" | "vi" | "vii"
ACCIDENTAL: /#{1,}|b{1,}/

inversion: INVERSION_STANDARD | inversion_free
INVERSION_STANDARD: "6" | "64" | "6/3" | "6/4" | "7" | "6/5" | "65" | "4/3" | "43" | "2" | "42" | "4/2" | "9" | "11" | "13"
inversion_free: ACCIDENTAL? DIGIT+

DIGIT: /[0-9]/
DIGITS: DIGIT+
LETTER: /[a-z]+/

REST_LINE: /.+/
PHRASE_BOUNDARY: WS "||" WS?

WS: (" " | /\t/)+
CR: /\r/
LF: /\n/
NEWLINE: WS* (CR? LF)+

%ignore NEWLINE
%ignore CR
%ignore LF
%ignore PHRASE_BOUNDARY
%ignore WS